"""added changes

Revision ID: e0fbacbf954f
Revises: 96abb4cf1b80
Create Date: 2026-01-11 00:05:41.362961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fbacbf954f'
down_revision: Union[str, Sequence[str], None] = '96abb4cf1b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('reservations', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('reservations', 'created_at')
    op.drop_column('bills', 'created_at')
    # ### end Alembic commands ###
